### PR TITLE
Update erlc_paths for Gleam v0.25.0

### PR DESCRIPTION
**Pull request by silicium14**
Fixes https://github.com/gleam-lang/mix_gleam/issues/26 but is not compatible with earlier gleam versions.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Hi there! I'm not familiar with this project or Mix, but could we specify both the old and the new path?

**Comment by silicium14** [comment]
> Hi there! I'm not familiar with this project or Mix, but could we specify both the old and the new path?

Totally, I don't know why I didn't think of it. I updated the branch and tested that it works with gleam 0.24.0 and 0.25.0.

**Comment by lpil** [comment]
Thank you, looks great!

ping @gleam-lang/elixir-team

**Review by tynanbe — APPROVED** [review]

**Comment by tynanbe** [comment]
Thank you!

**Pull request merged**
